### ISSUE TITLE
Does not build

### ISSUE THREAD

**Issue by benckx** [gurkenlabs/litiengine-gurk-nukem#5]
```
➜  litiengine-gurk-nukem-0.0.2 ./gradlew clean build
Downloading https://services.gradle.org/distributions/gradle-5.0-bin.zip
.................................................................................
Unzipping /home/benoit/.gradle/wrapper/dists/gradle-5.0-bin/pu5208521seraqlersebvqk/gradle-5.0-bin.zip to /home/benoit/.gradle/wrapper/dists/gradle-5.0-bin/pu5208521seraqlersebvqk
Set executable permissions for: /home/benoit/.gradle/wrapper/dists/gradle-5.0-bin/pu5208521seraqlersebvqk/gradle-5.0/bin/gradle

Welcome to Gradle 5.0!

Here are the highlights of this release:
 - Kotlin DSL 1.0
 - Task timeouts
 - Dependency alignment aka BOM support
 - Interactive `gradle init`

For more details see https://docs.gradle.org/5.0/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':distTar'.
> Could not resolve all task dependencies for configuration ':runtimeClasspath'.
   > Could not resolve project :litiengine.
     Required by:
         project :
      > Unable to find a matching configuration of project :litiengine: None of the consumable configurations have attributes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s
```

**Comment by AZ-0** [comment]
Duplicate already solved [issue #4](https://github.com/gurkenlabs/litiengine-gurk-nukem/issues/4) :wink:

**Comment by benckx** [comment]
Now I got this one. I'll have a look.

```
➜  litiengine-gurk-nukem-0.0.2 ./gradlew clean build 

> Task :compileJava FAILED
/home/benoit/Tuto/litiengine-gurk-nukem-0.0.2/src/com/litiengine/gurknukem/Player.java:15: error: cannot find symbol
import de.gurkenlabs.litiengine.physics.CollisionType;
                                       ^
  symbol:   class CollisionType
  location: package de.gurkenlabs.litiengine.physics
/home/benoit/Tuto/litiengine-gurk-nukem-0.0.2/src/com/litiengine/gurknukem/abilities/Jump.java:31: error: cannot find symbol
      super(ability, ability.getAttributes().getValue().getCurrentValue().intValue(), EffectTarget.EXECUTINGENTITY);
                                            ^
  symbol:   method getValue()
  location: class AbilityAttributes
/home/benoit/Tuto/litiengine-gurk-nukem-0.0.2/src/com/litiengine/gurknukem/Player.java:84: error: cannot find symbol
    return Game.physics().collides(groundCheck, CollisionType.STATIC);
                                                ^
  symbol:   variable CollisionType
  location: class Player
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
2 actionable tasks: 2 executed
```

**Comment by benckx** [comment]
* `CollisionType` has been renamed to `Collision` 
* `ability.getAttributes().getValue().getCurrentValue().intValue()` must be replaced by `ability.getAttributes().value().get()`

**Comment by benckx** [comment]
It works for the version found at https://codeload.github.com/gurkenlabs/litiengine-gurk-nukem/zip/v0.0.2, but the master branch here has other issues.

**Comment by benckx** [comment]
I was able to find a few fixes for the master branch here, but it looks like the map rendering API is too different and I can not find what is what:
https://github.com/benckx/litiengine-gurk-nukem/commit/3356caf380d8c9d3011de081adaef9c3ea21a43f

It would be nice if this sample project could be compiled independently from the current local implementation of the engine.

**Comment by AZ-0** [comment]
I don't think you should compile from the master branch but from the latest stable version instead.
